#!/bin/bash

echo "🔍 OAuth Configuration Checker"
echo "============================"
echo ""
echo "Client ID: 392865621461-bf06rb26geqs6c487u0q3k4sbgj9gpoa.apps.googleusercontent.com"
echo ""
echo "Required Authorized JavaScript Origins:"
echo "--------------------------------------"
echo "http://localhost:8080"
echo "http://localhost:3000"
echo "https://web-installer.vercel.app"
echo "https://web-installer-ejep7ul39-ryan-wagers-projects.vercel.app"
echo "https://install.anava.ai"
echo ""
echo "Required Authorized Redirect URIs:"
echo "---------------------------------"
echo "http://localhost:8080"
echo "http://localhost:8080/"
echo "http://localhost:3000"
echo "http://localhost:3000/"
echo "https://web-installer.vercel.app"
echo "https://web-installer.vercel.app/"
echo "https://web-installer-ejep7ul39-ryan-wagers-projects.vercel.app"
echo "https://web-installer-ejep7ul39-ryan-wagers-projects.vercel.app/"
echo "https://install.anava.ai"
echo "https://install.anava.ai/"
echo ""
echo "To test locally:"
echo "1. Make sure ALL the above URIs are in your OAuth config"
echo "2. Run: node test-oauth.js"
echo "3. Complete the OAuth flow"
echo "4. Check if token is received"
echo ""
echo "To get current OAuth config via gcloud:"
echo "gcloud auth application-default login"
echo "Then we can use gcloud APIs to check/update OAuth config"